---
apiVersion: v1
kind: Service
metadata:
  name: caddy-test
  annotations:
    prometheus.io/port: '9180'
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: caddy-test